AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-sample

  Sample SAM Template for aws-sam-sample

Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        SampleEvientGet:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: SampleApi
  SampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
